@url=http://localhost:5000
@suffix=api/v1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJuaUBnbWFpbC5jb20iLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE1MTYyMzkwMjJ9.YNA58vj_f6rN_dxxCIkULJLE2KIqLyVLCfclD9HF4E8

GET {{url}}

###
GET {{url}}/{{suffix}}/administrators?email=nguyenvana@gmail.com
authorization: bearer {{accessToken}}


# -----------------
# user model
# -----------------

###
POST {{url}}/{{suffix}}/administrators/add
Content-Type: application/json
Authorization: bearer {{accessToken}}

{
  "full_name" : "Rimon",
  "phone_number":"0123456789",
  "email":"nirimon@gmail.com",
  "role": "admin",
  "password" :"123456789"
}

###
POST {{url}}/{{suffix}}/administrators/update
Content-Type: application/json
authorization: bearer {{accessToken}}

{
  "full_name" : "Nurul I"
}

###
POST {{url}}/{{suffix}}/administrators/login
Content-Type: application/json

{
  "email":"ni@gmail.com",
  "password" :"nur"
}

# -----------------
# help request model
# -----------------
###
GET  {{url}}/{{suffix}}/help-request?budget_min=400
Content-Type: application/json
Authorization: bearer {{accessToken}}

###
POST {{url}}/{{suffix}}/help-request/add
Content-Type: application/json

{
  "platform_name": "Elite Commerce",
  "client_name": "Nurul Islam Rimon",
  "phone_number": "01710000000",
  "email": "nirimonbd@gmail.com",
  # "budget_min": 400,
  # "budget_max": 500,
  "project_description": "This will be the best project if you want!"
}
###
DELETE {{url}}/{{suffix}}/help-request/1
Content-Type: application/json
Authorization: bearer {{accessToken}}
